### ISSUE TITLE
Use Network Security Configuration instead of full Cleartext Traffic

### ISSUE THREAD

**Issue by starr0stealer** [SocketMobile/stockcount-android#42]
Regarding PR #41 

If using an HTTPS endpoint is not an option, then rather than using Cleartext Traffic at the App level, you should use [Network Security Configuration](https://developer.android.com/training/articles/security-config) at the domain level.

Granted this is just a sample app project, best practices should still be followed, especially in regards to security.

**Comment by doubleo2** [comment]
@starr0stealer You are absolutely right. Thank you for bringing this to our attention. 

If you have a minute, I'd really appreciate it if you could take a look at #43 and give it a 👍 if it looks good to you. In keeping with the principle of least privilege, I tried restricting cleartext traffic even further but there doesn't seem to be a way to specify a port.
